### ISSUE TITLE
Plugin crashes after activation

### ISSUE THREAD

**Issue by mkocus** [greenrivers/grav-plugin-webp#1]
I've tried to activate your plugin using grav admin menu, have installed all requirements.

It crashes whole grav (both page and admin menu) on webp.php here:
```
public function onPagesInitialized()
    {
        /** @var SessionInterface $session */
        $session = $this->grav['session'];

        /** @var Uri $uri */
        $uri = $this->grav['uri'];

        $paths = $uri->paths();

        if ($paths[2] === 'webp' && $paths[3]) {   /** CRASH HERE */
```
because the `$paths` length is 3, so it cannot access `$paths[3]`

**Comment by MajorKuprich** [comment]
Hello,

Thank You for catching this bug :-)
Fixed in [commit](https://github.com/greenrivers/grav-plugin-webp/commit/11d2455a9397dcd3bffbf727aa6fb45a19c8d346).
