### ISSUE TITLE
install packages: libwebp-dev, webp

### ISSUE THREAD

**Issue by mdestafadilah** [greenrivers/grav-plugin-webp#10]
what's is this? grav plugin or server plugin?

**Comment by MajorKuprich** [comment]
Hi @mdestafadilah,

These are system packages require for Webp conversion.

For example in Debian: 
https://packages.debian.org/sid/libwebp-dev
https://packages.debian.org/sid/webp

Webp docs:
https://developers.google.com/speed/webp#webp_support

Cheers

**Comment by mdestafadilah** [comment]
Confirmed, like your direction, just install and enable ini exiff plugin like [windows do](https://github.com/greenrivers/grav-plugin-webp/issues/11#issuecomment-1694275941)
