### ISSUE TITLE
Nothing to work in Ubuntu  or Windows Env

### ISSUE THREAD

**Issue by mdestafadilah** [greenrivers/grav-plugin-webp#11]
I'm using ubuntu and windows, both of them, i'm using apache with LAMP and Laragon.

but always show notice error 500 pages, like below

![24-08-2023 08-27-39](https://github.com/greenrivers/grav-plugin-webp/assets/5575882/1a0629a0-aa43-4b23-83d4-950aafd55f50)

before update, i'm using and not problem, now it' show this error.

**Comment by MajorKuprich** [comment]
Hello @mdestafadilah,

Similar to topic #9.
You need to install & enable PHP exif extension.
Description is [here](https://www.php.net/manual/en/exif.installation.php).

Updated docs available in new [release](https://github.com/greenrivers/grav-plugin-webp/releases/tag/1.4.4).

Regards

**Comment by mdestafadilah** [comment]
Thanks for confirmation, this is resolve just enabale exif.dll in php.ini. it's work now. may tomorrow i will test it in production environment with ubuntu server.
