### ISSUE TITLE
Unable to reach images using |webp

### ISSUE THREAD

**Issue by Fuficek** [greenrivers/grav-plugin-webp#15]
``I've tried using the webp plugin before and now I got stuck on the same issue. The images I want to display in webp are still jpgs. Even through I've converted them and they are saved in the folder webp in user. The functions '|webp' does not seem to work.

The following code displays the jpg version of the image
![image](https://github.com/greenrivers/grav-plugin-webp/assets/91286763/f2069efd-2f9f-46f5-ab7c-e0e1633a5807)
![image](https://github.com/greenrivers/grav-plugin-webp/assets/91286763/b7851787-f365-4ff3-bac3-f03d8281eead)

Any ideas why that might be?

All versions are up to date, cleared cache many times, and spent a week working on a workaround that kind of worked but is not in any way optimal. 

```
{% set pageMedia = page.media.images %}
{% if pageMedia|length > 0 %}
    {% set firstImage = pageMedia|first %}
    {% if firstImage.url|split('.')|last == 'webp' %}
        {% set webp_url = firstImage.url %}
        {% set webp_exists = file_exists(webp_url) %}
    {% else %}
        {% set webp_url = firstImage.url|replace({'/user/pages/': '/user/webp/user/pages/'})|replace({'.jpg': '.webp', '.jpeg': '.webp', '.png': '.webp', '.JPG' : '.webp'}) %}
        {% set webp_filename = webp_url|split('/')|last %}
        {% set file_path_array = webp_url|split('/') %}
        {% set file_path_array = file_path_array|slice(0, -1) %}
        {% set webpFilePath = file_path_array|join('/')  %}
        {% set webp_exists = file_exists(webpFilePath ~ webp_filename) %}
    {% endif %}
    {% if file_exists(webpFilePath ~ webp_filename) %}
        <img class="l3-img effectscroll_3" src="{{ webp_url }}" alt="{{ firstImage.alt }}" />
    {% else %}
        <img class="l3-img effectscroll_3" src="{{ firstImage.url }}" alt="{{ firstImage.alt }}" />
    {% endif %}
{% endif %}
```
_this worked until the plugin file_exists stopped cooperating_ :(

**Comment by MajorKuprich** [comment]
Hello @Fuficek,

At the first make sure that You met the requirements from the docs: https://github.com/greenrivers/grav-plugin-webp#requirements

Did You clear cache after convert images?

Could You provide info about:
- PHP version
- Grav version
- webp version from command line: cwebp --version

Regards

**Comment by MajorKuprich** [comment]
It has been 1 month since last activity in this topic, so I close this issue.
Reopen or create new ticket if You need more explanations, please. :)
