### ISSUE TITLE
Plugin don't convert images

### ISSUE THREAD

**Issue by tomceek** [greenrivers/grav-plugin-webp#4]
After installation plugin showed that images exist for conversion. after "conversion" there are no images to convert, but images .jpg and .png (as I have in the pages) are not converted, so the plugin doesn't work for me.

![image](https://user-images.githubusercontent.com/30144585/117448847-eb4a8380-af47-11eb-9c5b-34186f4bb3b4.png)
![image](https://user-images.githubusercontent.com/30144585/117448881-f69daf00-af47-11eb-9138-44210459d833.png)

Grav and plugins are up to date.

**Comment by MajorKuprich** [comment]
Hi @tomceek,
Sorry for late reply.

Did You clear cache after convert images? 
After conversion, You should see webp images in newly created folder: **webp** (from root Grav project directory).
Can You see them?

Could You provide info about:
- PHP version
- Grav version
- webp version from command line: `cwebp --version`

**Comment by tomceek** [comment]
PHP Version 7.4.14
Grav v1.7.14
Webp enabled - I don't have ssh access to check cwebp version remotely.

I have found new folder and generated images. Thanks for clarification.

Have few questions :) 
- Why it generates bunch of new folders and not convert directly to existing folders? 
- Also, for ex., jpg image size increased from 200KB to 640KB after conversion, it is normal?
- How to get webp module to work with this type of code?
`<a href="{{ item.url }}">{{ image_first.cropZoom(400,300).html() }}</a>`

**Comment by MajorKuprich** [comment]
* _Why it generates bunch of new folders and not convert directly to existing folders?_

In this way we get 2 separates areas (first for app sources, second for converted images by plugin). It allows distinguish app from its new changes.

* _Also, for ex., jpg image size increased from 200KB to 640KB after conversion, it is normal?_

No, it's not correct behaviour. Size may increase slightly depending on type and method of conversion (reference: https://developers.google.com/speed/webp/docs/cwebp#options). However, more than threefold increase is far too much.
You can send me one of example image in JPG I will look at it.

* _How to get webp module to work with this type of code?_
`<a href="{{ item.url }}">{{ image_first.cropZoom(400,300).html() }}</a>`

`<a href="{{ item.url }}">{{ image_first.cropZoom(400,300).format('webp').html() }}</a>` 
(reference: https://github.com/getgrav/grav/pull/3144)

**Comment by MajorKuprich** [comment]
It has been 3 months since last activity in this topic, so I close this issue.
Reopen or create new ticket if You need more explanations, please. :)
